version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./config.yaml:/app/config.yaml
      - ./src:/app/src
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ecommerce-network

  shopify_app:
    build:
      context: .
      dockerfile: Dockerfile.shopify
    ports:
      - "5000:5000"
    volumes:
      - ./shopify_app.py:/app/shopify_app.py
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production
      - ANALYTICS_API_URL=http://api:8000
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
